### ISSUE TITLE
Problem with laravel 5.6.3

### ISSUE THREAD

**Issue by brusselsregular** [nicolasbeauvais/laravel-botscout#5]
Hi, 

Thanks for creating this package! I tried to install it on Laravel 5.6.3 but got this error: 

`nicolasbeauvais/laravel-botscout 1.1.0 requires illuminate/contracts ~5.1.0|~5.2.0|~5.3.0|~5.4.0|~5.5.0 -> satisfiable by illuminate/contracts[v5.1.1, v5.1.13, v5.1.16

- Installation request for laravel/framework (locked at v5.6.3, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.3].`

Any ideas?

**Comment by nicolasbeauvais** [comment]
This issue should be fixed now, thank you
